{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubefence.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubefence.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
